# Generated by Django 3.1.6 on 2021-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='professor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='administrador',
            field=models.BooleanField(default=False, verbose_name='administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instrutor',
            field=models.BooleanField(default=False, verbose_name='instrutor'),
        ),
    ]
