# Generated by Django 3.1.6 on 2021-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0003_auto_20210513_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instrutor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_de_acesso',
            field=models.IntegerField(default=1, verbose_name='nivel'),
        ),
    ]
