# Generated by Django 3.1.6 on 2021-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0004_auto_20210514_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_de_acesso',
            field=models.IntegerField(default=1, verbose_name='nivel_de_acesso'),
        ),
    ]
