# Generated by Django 3.1.6 on 2021-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0005_auto_20210514_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('descricao', models.CharField(default='', max_length=255, null=True, verbose_name='descricao')),
            ],
        ),
    ]
