# Generated by Django 3.1.6 on 2021-05-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0007_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='image',
            new_name='imagem',
        ),
    ]
