# Generated by Django 3.1.6 on 2021-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0008_auto_20210515_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
