# Generated by Django 3.1.6 on 2021-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0009_auto_20210515_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='imagem',
            field=models.ImageField(upload_to='images/', verbose_name='imagem'),
        ),
    ]
