# Generated by Django 3.1.6 on 2021-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0012_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desabilitada',
            field=models.BooleanField(default=False, verbose_name='desabilitada'),
        ),
    ]
