# Generated by Django 3.2.2 on 2021-05-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0015_auto_20210521_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_video', models.CharField(default='', max_length=255, verbose_name='index_video')),
                ('index_banner', models.CharField(default='', max_length=255, verbose_name='index_video')),
            ],
        ),
    ]
