# Generated by Django 3.1.6 on 2021-05-22 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfit', '0016_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0, verbose_name='valor')),
                ('data', models.DateField(default=datetime.datetime(2021, 5, 22, 15, 35, 22, 535907), verbose_name='data')),
                ('tipo', models.IntegerField(default=0, verbose_name='tipo')),
                ('usuario_id', models.IntegerField(default=0, verbose_name='usuario_id')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email', max_length=250, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=250, verbose_name='nome'),
        ),
    ]
