# Generated by Django 3.1.5 on 2021-01-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='login'),
        ),
    ]
