# Generated by Django 3.1.5 on 2021-03-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210318_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='professor',
            field=models.BooleanField(default=False, verbose_name='professor'),
        ),
    ]
